2024-07-30 11:54:40,004 INFO    MainThread:14001 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_setup.py:_flush():76] Configure stats pid to 14001
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_setup.py:_flush():76] Loading settings from /Users/mmuhleth/.config/wandb/settings
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_setup.py:_flush():76] Loading settings from /Users/mmuhleth/Desktop/diffusion_graph/wandb/settings
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_ppgn_simple.py', 'program': '/Users/mmuhleth/Desktop/diffusion_graph/train_ppgn_simple.py'}
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_init.py:_log_setup():507] Logging user logs to /Users/mmuhleth/Desktop/diffusion_graph/wandb/run-20240730_115440-kgpcgo74/logs/debug.log
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/mmuhleth/Desktop/diffusion_graph/wandb/run-20240730_115440-kgpcgo74/logs/debug-internal.log
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_init.py:init():547] calling init triggers
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_init.py:init():596] starting backend
2024-07-30 11:54:40,005 INFO    MainThread:14001 [wandb_init.py:init():600] setting up manager
2024-07-30 11:54:40,009 INFO    MainThread:14001 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-30 11:54:40,013 INFO    MainThread:14001 [wandb_init.py:init():606] backend started and connected
2024-07-30 11:54:40,017 INFO    MainThread:14001 [wandb_init.py:init():703] updated telemetry
2024-07-30 11:54:40,017 INFO    MainThread:14001 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2024-07-30 11:54:40,287 ERROR   MainThread:14001 [wandb_init.py:init():762] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-30 11:54:40,343 ERROR   MainThread:14001 [wandb_init.py:init():1170] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/digress/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/opt/anaconda3/envs/digress/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-30 11:54:41,351 WARNING MsgRouterThr:14001 [router.py:message_loop():77] message_loop has been closed
